{"name": "test_login_fail_form_error[data3]", "status": "passed", "attachments": [{"name": "log", "source": "993f3d14-6b96-4b62-92ec-c232802edd0c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553112', 'password': 'python', 'check': '请输入正确的手机号'}"}], "start": 1567138258982, "stop": 1567138259719, "uuid": "5cbe2a14-9daa-4e03-b10c-4e9ca929cce6", "historyId": "4845c1cf830728e359e891f2a8ac5db7", "testCaseId": "d9574c1722641d515e9f2f722dc354c5", "fullName": "testcases.test_login6.Test_Login#test_login_fail_form_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login6"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "liliangdeMacBook-Pro.local"}, {"name": "thread", "value": "68435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login6"}]}