{"name": "test_login_fail_middle_error[data0]", "status": "passed", "attachments": [{"name": "log", "source": "39e42016-a202-4a4b-83a1-d5d196bcd2b1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18392628352', 'password': '123456', 'check': '此账号没有经过授权，请联系管理员!'}"}], "start": 1567138260958, "stop": 1567138261814, "uuid": "a7d1cca5-b17c-4604-8010-3319fc757082", "historyId": "a9ff1ef0a542f208180b91d19a396a5e", "testCaseId": "70c962baa2b57419f3fcc0ee3a86d9ec", "fullName": "testcases.test_login6.Test_Login#test_login_fail_middle_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login6"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "liliangdeMacBook-Pro.local"}, {"name": "thread", "value": "68435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login6"}]}